### ISSUE TITLE
migrate trpc from v9 to v10

### ISSUE THREAD

**Issue by voidcoefficient** [minsk-dev/t3-cli#1]
## TODO LIST

- [x] t variable
- [ ] full example t variable?
- [ ] defining routes & procedures
- [ ] calling procedures
- [ ] inferring types
- [ ] middleware

### client package changes

- [ ] upgrade of `react-query`
- [ ] [tRPC-specific options on hooks moved to `trpc`](https://trpc.io/docs/v10/migrate-from-v9-to-v10#trpc-specific-options-on-hooks-moved-to-trpc)
- [ ] aborting procedures
- [ ] http-specific options moved from `TRPCClient` to links
